### ISSUE TITLE
helicsEndpointSendMessageObject and helicsEndpointSendMessageObjectZeroCopy incorrectly call helicsEndpointSendMessage

### ISSUE THREAD

**Issue by afisher1** [GMLC-TDC/pyhelics#10]
The deprecated functions, helicsEndpointSendMessageObject and helicsEndpointSendMessageObjectZeroCopy incorrectly call helicsEndpointSendMessage as they both fail to pass the message argument to that function call resulting in an missing argument error.

**Comment by kdheepak** [comment]
You are right! Wow, not sure how that slipped through. Thanks for submitting a fix! I've merged your PR into `master`.

**Comment by afisher1** [comment]
Thanks.
