### ISSUE TITLE
HELICS library error message not passing to federate log file

### ISSUE THREAD

**Issue by trevorhardy** [GMLC-TDC/pyhelics#13]
@phlptp has confirmed that the HELICS library generates error messages back to the federate when sending messages to an invalid endpoint (as was being done [in this older version of this example](https://github.com/GMLC-TDC/HELICS-Examples/tree/ddc9a6b83c0ea32b3399de7a08ac8fda0d7d1a52)). This error message is not making it all the way to the federate log when using pyhelics.

**Comment by kdheepak** [comment]
This should be resolved now I believe.
