### ISSUE TITLE
Suppress warning about upcoming type change in HelicsInput.complex

### ISSUE THREAD

**Issue by wfvining** [GMLC-TDC/pyhelics#15]
https://github.com/GMLC-TDC/pyhelics/blob/0d3ce3a9c15d04478c240cb356d5c9718c0dd32f/helics/capi.py#L2041-L2044

The call to `helicsInputGetComplex()` issues a `UserWarning` with the message "This function will return a complex number in the next major release". Since the "pythonic" API is already converting the output of this function to a `complex` number, this warning is misleading/surprising here.

I think the `warnings.catch_warnings` context manager would be useful here to filter this warning just from this call, and restore the previous warnings filter/configuration after returning.

**Comment by kdheepak** [comment]
Great idea! Thanks for the suggestion! I can make the change later this evening but if you’d like to make a PR that would work too!
