### ISSUE TITLE
HelicsFederate.endpoints does not contain endpoints from config file

### ISSUE THREAD

**Issue by wfvining** [GMLC-TDC/pyhelics#19]
When a `HelicsMessageFederate` (or a `HelicsCombinationFederate`) is created with `helicsCreateMessageFederateFromConfig()`, the `endpoints` field does not include any of the endpoints from the config file. For example:

```json
{
  "name": "foo",
  "endpoints": [
    {
        "name": "ep"
    }
  ]
}
```

```python
from helics import helicsCreateMessageFederateFromConfig
fed = helicsCreateMessageFederateFromConfig("foo.json")
# this raises a KeyError
fed.endpoints["ep"]
# this returns the endpoint
fed.get_endpoint_by_name("ep")
```

It would be nice to have uniform handling of endpoints registered via `fed.register_endpoint()` and endpoints registered by the config file, the same as publications and inputs.

**Comment by kdheepak** [comment]
Thanks for opening the issue! I meant to fix this but didn't get around to it. It should work as you expect it now. I'll make a new pypi release shortly.
