### ISSUE TITLE
Logging discrepancy

### ISSUE THREAD

**Issue by trevorhardy** [GMLC-TDC/pyhelics#21]
Under the v3beta, two of the User Guide examples that are very similar have different logging behaviors:

* [Fundamental default example](https://github.com/GMLC-TDC/HELICS-Examples/tree/master/user_guide_examples/fundamental/fundamental_default)- only one logging message per logging event; this is the desired behavior
```
Entered HELICS execution mode
Requesting time 60
Granted time 60.0
Battery 1 time 60.0
```

* [Fundamental endpoint example](https://github.com/GMLC-TDC/HELICS-Examples/tree/master/user_guide_examples/fundamental/fundamental_message_comm/endpoints) is similar but uses messages instead of pub/sub and produces two logging messages per logging event; this is not the desired behavior
```
Entered HELICS execution mode
INFO:__main__:Entered HELICS execution mode
Requesting time 70
DEBUG:__main__:Requesting time 70
Granted time 70.0
DEBUG:__main__:Granted time 70.0
Battery 1 time 70.0
DEBUG:__main__:Battery 1 time 70.0
```

I'm assuming this is a PyHELICS thing but I'm not sure. I've looked at the two config files and the runner config and I'm not seeing any differences that would explain what's happening.

**Comment by kdheepak** [comment]
The link in your second bullet point is missing. However, I think this is issue that is associated with configuring the built in Python logging module and not a `pyhelics` issue.

**Comment by trevorhardy** [comment]
Added link to the bug report; good catch.

I think I agree in as I've tested other [examples with endpoints that exhibit this behavior:](https://github.com/GMLC-TDC/HELICS-Examples/tree/master/user_guide_examples/fundamental/fundamental_message_comm/combo).

I'm going to leave this issue open and re-assign it to myself.

**Comment by kdheepak** [comment]
Change this line:

https://github.com/GMLC-TDC/HELICS-Examples/blob/a906ac9beff0cbdd2df5511c5b7518d754b8164b/user_guide_examples/fundamental/fundamental_message_comm/endpoints/Charger.py#L106

from:

```
logging.debug(f'\tNumber of endpoints: {end_count}')
```

to

```
logger.debug(f'\tNumber of endpoints: {end_count}')
```

Similar changes here: https://github.com/GMLC-TDC/HELICS-Examples/blob/a906ac9beff0cbdd2df5511c5b7518d754b8164b/user_guide_examples/fundamental/fundamental_message_comm/endpoints/Battery.py#L81

That is definitely one part of the problem. I think that'll fix it. If it doesn't we can take a closer look during the working meeting.

**Comment by trevorhardy** [comment]
That was it!

I knew it was something stupid like that and should have suspected my code first. Thanks for the help.
