### ISSUE TITLE
`helicsFederateDisconnect()` not supported?

### ISSUE THREAD

**Issue by trevorhardy** [GMLC-TDC/pyhelics#22]
`helicsFederateDisconnect()` is the API replacing `helicsFederateFinalize()` but it doesn't appear supported in pyhelics 2.7.1.

```
  File "Controller.py", line 38, in destroy_federate
    status = h.helicsFederateDisconnect(fed)
AttributeError: module 'helics' has no attribute 'helicsFederateDisconnect'
```

**Comment by kdheepak** [comment]
Thanks for spotting this and opening issues. This is fixed and will be part of the next release.
