### ISSUE TITLE
v3 logging levels appropriately supported?

### ISSUE THREAD

**Issue by trevorhardy** [GMLC-TDC/pyhelics#23]
Its not clear to me if the new HELICS library logging levels are being appropriately supported in pyhelics 2.7.1. It seems like I'm able to get away with not using a valid logging level (e.g. "1") when I thought that was deprecated in HELICS v3.

**Comment by kdheepak** [comment]
Thanks for spotting this and opening issues. This is fixed and will be part of the next release. 

You can use `h.HelicsLogLevel.WARNING` or `h.HELICS_LOG_LEVEL_NO_PRINT` and it should work the same in v2 and v3.
