### ISSUE TITLE
macOS platform tag changes

### ISSUE THREAD

**Issue by nightlark** [GMLC-TDC/pyhelics#35]
The current HELICS 3.x installers require macos 10.14, so we should update the platform tag in compiled wheels to reflect that (instead of 10.9).

Another upcoming change will be when we start releasing universal macOS binaries, the name of the macOS binary downloaded (and the platform tag) will need updating again. The tags used by the CMake python package are `macosx_10_9_universal2.macosx_10_9_x86_64.macosx_11_0_arm64.macosx_11_0_universal2`, so we should consider a similar set along the lines of `macosx_10_14_universal2.macosx_10_14_x86_64.macosx_11_0_arm64.macosx_11_0_universal2`

**Comment by trevorhardy** [comment]
@nightlark; has this been resolved?

**Comment by nightlark** [comment]
It seems to be done.

**Comment by trevorhardy** [comment]
Closing out.
