### ISSUE TITLE
Return all types using `.value` in HelicsInput

### ISSUE THREAD

**Issue by josephmckinsey** [GMLC-TDC/pyhelics#39]
The pythonic API for HelicsInput should allow a general `.value` property that converts to the type given by `.type`.

**Comment by kdheepak** [comment]
I think this can also be a source of unexpected bugs when a function doesn't return just one type. Users might prototype in the REPL, write some code that works now but later fails when the input type changes. That said, I think the ease of use when prototyping may make it worth it, so I'm inclined to add it. I made a PR with this change, but I'll add tests before merging.
