### ISSUE TITLE
Helics-apps is at version 3.3.1, while helics[cli] is at version 3.3.0.post0

### ISSUE THREAD

**Issue by Astarry** [GMLC-TDC/pyhelics#62]
Helics-apps is at version 3.3.1, while helics[cli] is at version 3.3.0.post0. This is throwing the error 
[warn] `helics` and `helics-apps` versions don't match. You may want to run `pip install helics helics-apps --upgrade`.

**To Reproduce**

- [ ] Reproducible using test suite located here: <https://github.com/GMLC-TDC/pyhelics/blob/main/tests/test_python_api.py>

**Environment (please complete the following information):**

- Operating System: 
- Installation: 
- helics and pyhelics version:

```
helics --version
```

Share the output of the following:

```
$ python -c "import helics as h; import json; print(json.dumps(h.helicsGetSystemInfo(), indent=4, sort_keys=True))"
```

**Additional context and information**

**Comment by kdheepak** [comment]
The latest pyhelics (and for a few versions now) have `helics-apps` unbundled in them. See:

https://github.com/GMLC-TDC/pyhelics/blob/8b4f4a243d70c64460cd68e7f32be6c7e8db6b56/setup.py#L648-L652

The way it works is that when we build a whl for pyhelics, we build the library as well as the apps, and that is installed on your machine, and that is exposed at entrypoints from setup.py in the lines above. Is there a reason you want to install helics-apps as well as pyhelics?

pyhelics needs to be updated to 3.1.1 though, but that is a separate issue.

**Comment by kdheepak** [comment]
ping @nightlark

**Comment by nightlark** [comment]
Some addAlias functions were added to the C API in 3.3.1 that need to be added to pyhelics.

**Comment by Astarry** [comment]
It wasn't clear to me that installing helics in a setup.py file would install the helics-app as well. Thank you.

**Comment by nightlark** [comment]
pyhelics packages for HELICS 3.3.1 and 3.3.2 have been published.

I think @kdheepak means that the main helics package now includes its own copy of the binaries.
