### ISSUE TITLE
Prefer `main` branch instead of `develop` branch

### ISSUE THREAD

**Issue by kdheepak** [GMLC-TDC/pyhelics#71]
pyhelics development hasn't used git flow in the past, and using a `develop` branch is not required.

Right now there are 3 commits that are on develop that are not a `main`.

<img width="1268" alt="image" src="https://github.com/GMLC-TDC/pyhelics/assets/1813121/b1d055dd-009b-4894-a6ac-64152f5f6edd">

Let me know if you want me to fix that and cherry pick those commits to `main`. After that the `develop` branch can probably be deleted to prevent any confusion.

**Comment by trevorhardy** [comment]
Got for it; I didn't intend to rock the boat.
