### ISSUE TITLE
Library load bug in 3.0.0-alpha.2

### ISSUE THREAD

**Issue by eberleim** [GMLC-TDC/pyhelics#8]
If HELICS v3.0.0-alpha.2 was built and installed with the C++ library active, the logic in `_build.py` responsible for library loading will accidentally bind and load the C++ shared library instead of the C shared library, breaking some bindings. 
The responsible line appears to be `if "libhelics" in file:` on MacOS (other operating systems may share similar bug after shared library renames). 
Modifying the line as follows resolved the issue on MacOS, however this may not be the desired solution: `if "libhelics" in file and not "cpp" in file:`

**Comment by kdheepak** [comment]
This should be resolved in the latest version.
